"""Add API usage log model

Revision ID: a87e1b19a0e5
Revises: 
Create Date: 2025-05-25 11:20:19.292639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87e1b19a0e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=False),
    sa.Column('response_payload', sa.Text(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_api_usage_logs_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('humanizers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultra_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humanizers', schema=None) as batch_op:
        batch_op.drop_column('ultra_mode')

    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
